fork = false
frame = "transparent"
idle = true
maximized = true
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = true
wsl = false

[font]
normal = ["JetBrains Mono"] # Will use the bundled Fira Code Nerd Font by default
size = 18.0
